# Generated by Django 5.1.3 on 2025-07-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_testimonials'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonials',
            old_name='user_name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='testimonials',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='home/user/'),
        ),
    ]
