# Generated by Django 5.1.3 on 2025-07-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_user_name_testimonials_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/menu/item/'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/home/user/'),
        ),
    ]
